<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="60099" started-at="2020-09-24T14:47:35Z" finished-at="2020-09-24T14:48:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="60099" started-at="2020-09-24T14:47:35Z" finished-at="2020-09-24T14:48:35Z">
      <class name="emp.attendence.AttendenceTest">
        <test-method status="PASS" signature="Start()[pri:0, instance:emp.attendence.AttendenceTest@6e1567f1]" name="Start" is-config="true" duration-ms="27541" started-at="2020-09-24T14:47:35Z" finished-at="2020-09-24T14:48:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method status="FAIL" signature="OpenAttendPage()[pri:0, instance:emp.attendence.AttendenceTest@6e1567f1]" name="OpenAttendPage" duration-ms="32497" started-at="2020-09-24T14:48:02Z" finished-at="2020-09-24T14:48:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Thu Sep 24 17:48:35 EEST 2020> but was:<0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Thu Sep 24 17:48:35 EEST 2020> but was:<0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at emp.attendence.AttendenceTest.OpenAttendPage(AttendenceTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenAttendPage -->
      </class> <!-- emp.attendence.AttendenceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
